name: CD with CodeDeploy (in-place)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar --exclude-task test

      # Secrets로 application-private.properties 생성 (파일은 ZIP에만 포함되고 Git에는 미커밋)
      - name: Create application-private.properties from secrets
        run: |
          mkdir -p bundle
          cat > bundle/application-private.properties <<EOF
          server.port=${{ secrets.SERVER_PORT }}
          spring.application.name=sawonz

          spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
          spring.datasource.url=jdbc:mysql://${{ secrets.DB_ENDPOINT }}/${{ secrets.DB_NAME }}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
          spring.datasource.username=${{ secrets.DB_USER }}
          spring.datasource.password=${{ secrets.DB_PASSWORD }}

          spring.jpa.hibernate.ddl-auto=update
          spring.jpa.show-sql=true
          spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
          spring.mail.host=smtp.gmail.com
          
          spring.mail.port=587
          spring.mail.username=${{ secrets.MAIL_USERNAME }}
          spring.mail.password=${{ secrets.MAIL_PASSWORD }}
          spring.mail.properties.mail.smtp.auth=true
          spring.mail.properties.mail.smtp.starttls.enable=true
          spring.mail.default-encoding=UTF-8
          
          app.jwt.secret=${{ secrets.JWT_SECRET }}
          app.jwt.access-exp-min=60
          app.jwt.refresh-exp-min=720
               
          app.cookie.domain=${{ secrets.COOKIE_DOMAIN }}
          app.cookie.secure=true
          app.cookie.same-site=None
          app.cookie.path=/
          
          # 계정 등록 ON/OFF 스위치
          app.seed.enabled=true
          
          # 계정 목록 (인덱스 기반)
          app.seed.users[0].email=test_admin@sawonz.world
          app.seed.users[0].name=testadmin
          app.seed.users[0].role=ROLE_ADMIN
          app.seed.users[0].password=admin123!!
          
          app.seed.users[1].email=test_manager@sawonz.world
          app.seed.users[1].name=testmanager
          app.seed.users[1].role=ROLE_MANAGER
          app.seed.users[1].password=manager123!!
          
          app.seed.users[2].email=test_member@sawonz.world
          app.seed.users[2].name=testuser
          app.seed.users[2].role=ROLE_MEMBER
          app.seed.users[2].password=member123!!
          EOF

      - name: Prepare bundle
        run: |
          mkdir -p bundle/scripts
          cp appspec.yml bundle/
          cp -r scripts/* bundle/scripts/
          chmod +x bundle/scripts/*.sh
          JAR=$(ls build/libs/*.jar | head -n 1)
          cp "$JAR" bundle/sawonz-backend.jar
          cd bundle && zip -r ../deploy-latest.zip . && cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp deploy-latest.zip s3://${{ secrets.AWS_CODEDEPLOY_BUCKET }}/sawonz/deploy-latest.zip

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name "${{ secrets.CODEDEPLOY_APP_NAME }}" \
            --deployment-group-name "${{ secrets.CODEDEPLOY_GROUP_NAME }}" \
            --s3-location bucket=${{ secrets.AWS_CODEDEPLOY_BUCKET }},key=sawonz/deploy-latest.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE \
            --ignore-application-stop-failures \
            --region "${{ secrets.AWS_REGION }}"
